from perso.perso import Personnage
from perso.perso import Mob
from perso.mechants import *
from perso.gentils.chevalier import Chevalier
from perso.gentils.elfe import Elfe
from perso.gentils.sorcier import Sorcier
from perso.mechants.loupGarou import LoupGarou
from perso.mechants.vampire import Vampire
from perso.mechants.troll import Troll
